INSERT INTO winning_players (full_name, position, nationality)
VALUES
('Aaron Mooy','Midfielder','Australia'),
('Abdalla Mahmoud El Said Bekhit','Midfielder','Egypt'),
('Abdiel Arroyo Molinar','Forward','Panama'),
('Abdoulaye Diallo','Goalkeeper','Senegal'),
('Abdullah Alkhaibari','Midfielder','Saudi Arabia'),
('Abdullah Ibrahim Al Maiouf','Goalkeeper','Saudi Arabia'),
('Abdullah Ibrahim Otayf','Midfielder','Saudi Arabia'),
('Abdullahi Shehu','Defender','Nigeria'),
('Abdulmalek Abdullah Al Khaibri','Midfielder','Saudi Arabia'),
('Abel Enrique Aguilar Tapia','Midfielder','Colombia'),
('Achraf Hakimi Mouh','Defender','Morocco'),
('Adama Mbengue','Midfielder','Senegal'),
('Adil Rami','Defender','France'),
('Adnan Januzaj','Midfielder','Belgium'),
('Adolfo Abdiel Machado','Defender','Panama'),
('Adrien Sebastian Perruchet Silva','Midfielder','Portugal'),
('Ahmed Eissa El Mohamady Abdel Fattah','Midfielder','Egypt'),
('Ahmed Fathy Abdel Meneim Ibrahim','Defender','Egypt'),
('Ahmed Hegazi','Defender','Egypt'),
('Ahmed Khalil','Midfielder','Tunisia'),
('Ahmed Musa','Forward','Nigeria'),
('Ahmed Reda Tagnaouti','Goalkeeper','Morocco'),
('Alan Dzagoev','Midfielder','Russia'),
('Albert Gudmundsson','Midfielder','Iceland'),
('Albin Ekdal','Midfielder','Sweden'),
('Aleksandar Kolarov','Defender','Serbia'),
('Aleksandr Erokhin','Midfielder','Russia'),
('Aleksandr Golovin','Midfielder','Russia'),
('Aleksey Miranchuk','Midfielder','Russia'),
('Alex Iwobi','Forward','Nigeria'),
('Alexandr Samedov','Midfielder','Russia'),
('Alfred Gomis','Goalkeeper','Senegal'),
('Alfred John Momar N Diaye','Midfielder','Senegal'),
('Ali Albulayhi','Defender','Saudi Arabia'),
('Ali Gabr','Defender','Egypt'),
('Alireza Jahanbakhsh','Forward','Iran'),
('Alireza Safar Beiranvand','Goalkeeper','Iran'),
('Alisson Becker','Goalkeeper','Brazil'),
('Alphonse Areola','Goalkeeper','France'),
('Amine Harit','Midfielder','France'),
('Amir Abedzadeh','Goalkeeper','Iran'),
('Amr Medhat Warda','Midfielder','Egypt'),
('Andreas Christensen','Defender','Denmark'),
('Andreas Cornelius','Forward','Denmark'),
('Andreas Granqvist','Defender','Sweden'),
('Andrew Nabbout','Forward','Australia'),
('Andrey Lunev','Goalkeeper','Russia'),
('Andrey Semenov','Defender','Russia'),
('Andy Jorman Polo Andrade','Forward','Peru'),
('Anice Badri','Forward','France'),
('Anthony Lopes','Goalkeeper','Portugal'),
('Antoine Griezmann','Forward','France'),
('Anton Miranchuk','Midfielder','Russia'),
('Antonio Rukavina','Defender','Serbia'),
('Arkadiusz Milik','Forward','Poland'),
('Armando Enrique Cooper Whitaker','Midfielder','Panama'),
('Aron Einar Gunnarsson','Midfielder','Iceland'),
('Artem Dzyuba','Forward','Russia'),
('Ashkan Dejagah','Midfielder','Iran'),
('Ashley Young','Midfielder','England'),
('Axel Witsel','Midfielder','Belgium'),
('Ayman Ashraf','Defender','Egypt'),
('Aymen Mathlouthi','Goalkeeper','Tunisia'),
('Ayoub El Kaabi','Forward','Morocco'),
('Aziz Bouhaddouz','Forward','Morocco'),
('Aziz Eraltay Behich','Defender','Australia'),
('Ban-Suk Oh','Defender','South Korea'),
('Bartosz Bialkowski','Goalkeeper','Poland'),
('Bassem Srarfi','Midfielder','Tunisia'),
('Benjamin Mendy','Defender','France'),
('Benjamin Pavard','Defender','France'),
('Bernardo Silva','Midfielder','Portugal'),
('Birkir Bjarnason','Midfielder','Iceland'),
('Bjorn Sigurdarson','Forward','Iceland'),
('Blaise Matuidi','Midfielder','France'),
('Brad Jones','Goalkeeper','Australia'),
('Breel Embolo','Forward','Switzerland'),
('Brian Oladapo Idowu','Defender','Russia'),
('Bruno Alves','Defender','Portugal'),
('Bruno Miguel Borges Fernandes','Midfielder','Portugal'),
('Bryan Oviedo','Defender','Costa Rica'),
('Carlos Bacca','Forward','Colombia'),
('Carlos Salcedo','Defender','Mexico'),
('Carlos Vela','Forward','Mexico'),
('Casemiro','Defender','Luxembourg'),
('Cedric Soares','Defender','Portugal'),
('Celso Borges','Midfielder','Costa Rica'),
('Cesar Azpilicueta','Defender','Spain'),
('Cheikh N Doye','Midfielder','Senegal'),
('Chidozie Awaziem','Defender','Nigeria'),
('Christian Alberto Cueva Bravo','Midfielder','Peru'),
('Christian Eriksen','Midfielder','Denmark'),
('Chul Hong','Defender','South Korea'),
('Corentin Tolisso','Midfielder','France'),
('Cristhian Stuani','Forward','Uruguay'),
('Cristian Daniel Ansaldi','Defender','Argentina'),
('Cristian Gamboa Luna','Defender','Costa Rica'),
('Cristiano Ronaldo','Forward','Portugal'),
('Daler Kuzyaev','Midfielder','Russia'),
('Daniel Akpeyi','Goalkeeper','Nigeria'),
('Daniel Arzani','Forward','Australia'),
('Daniel Carvajal Ramos','Defender','Spain'),
('Daniel Colindres Solera','Forward','Costa Rica'),
('Danilo','Defender','Brazil'),
('Danny Rose','Defender','England'),
('Danny Welbeck','Forward','England'),
('David de Gea','Goalkeeper','Spain'),
('David Silva','Midfielder','Spain'),
('Dawid Kownacki','Forward','Poland'),
('Dedryck Boyata','Defender','Belgium'),
('Dejan Lovren','Defender','Croatia'),
('Dele Alli','Midfielder','England'),
('Denis Cheryshev','Midfielder','Russia'),
('Denis Zakaria','Midfielder','Switzerland'),
('Diafra Sakho','Forward','Senegal'),
('Diego Da Silva Costa','Forward','Spain'),
('Diego Laxalt','Midfielder','Uruguay'),
('Dimitri Petratos','Forward','Australia'),
('Domagoj Vida','Defender','Croatia'),
('Douglas Costa','Midfielder','Brazil'),
('Dries Mertens','Forward','Belgium'),
('Dylan Bronn','Defender','Tunisia'),
('Eden Hazard','Midfielder','Belgium'),
('Ederson','Goalkeeper','Brazil'),
('Edinson Cavani','Forward','Uruguay'),
('Eduardo Antonio Salvio','Midfielder','Argentina'),
('Ehsan Hajsafi','Midfielder','Iran'),
('Eiji Kawashima','Goalkeeper','Japan'),
('Elderson Uwa Echiejile','Defender','Nigeria'),
('Ellyes Skhiri','Midfielder','France'),
('Emil Forsberg','Forward','Sweden'),
('Emil Krafth','Defender','Sweden'),
('Eric Dier','Midfielder','England'),
('Erick Javier Davis Grajales','Defender','Panama'),
('Essam Kamal Tawfik El Hadary','Goalkeeper','Egypt'),
('Fabian Delph','Midfielder','England'),
('Fahad Mosaed Al Muwallad Al Harbi','Forward','Saudi Arabia'),
('Fakhreddine Ben Youssef','Forward','Tunisia'),
('Farouk Ben Mustapha','Goalkeeper','Tunisia'),
('Faustino Marcos Alberto Rojo','Defender','Argentina'),
('Federico Fazio','Defender','Argentina'),
('Fedor Kudryashov','Defender','Russia'),
('Ferjani Sassi','Midfielder','Tunisia'),
('Fernando Luiz Rosa','Midfielder','Brazil'),
('Fidel Escobar Mendieta','Defender','Panama'),
('Filip Helander','Defender','Sweden'),
('Florian Thauvin','Midfielder','France'),
('Francis Odinaka Uzoho','Goalkeeper','Nigeria'),
('Francisco Javier Calvo Quesada','Defender','Costa Rica'),
('Franco Armani','Goalkeeper','Argentina'),
('Frederico Rodrigues Santos','Midfielder','Brazil'),
('Frederik August Albrecht Schram','Goalkeeper','Iceland'),
('Frederik R??nnow','Goalkeeper','Denmark'),
('Fyodor Smolov','Forward','Russia'),
('Gabriel Arturo Torres Tejada','Forward','Panama'),
('Gabriel Jesus','Forward','Brazil'),
('Gabriel Mercado','Defender','Argentina'),
('Gaku Shibasaki','Midfielder','Japan'),
('Gary Cahill','Defender','England'),
('Gelson Dany Batalha Martins','Forward','Portugal'),
('Gelson Fernandes','Midfielder','Switzerland'),
('Genki Haraguchi','Midfielder','Japan'),
('Ghilane Chalali','Midfielder','Tunisia'),
('Giorgian Daniel De Arrascaeta Benedetti','Midfielder','Uruguay'),
('Giovani Lo Celso','Midfielder','Argentina'),
('Gon??alo Guedes','Midfielder','Portugal'),
('Gonzalo Higuain','Forward','Argentina'),
('Gotoku Sakai','Defender','Japan'),
('Granit Xhaka','Midfielder','Switzerland'),
('Grzegorz Krychowiak','Midfielder','Poland'),
('Guillermo Varela Olivera','Defender','Uruguay'),
('Gustav Svensson','Midfielder','Sweden'),
('Gylfi Sigurdsson','Midfielder','Iceland'),
('Hakim Ziyech','Midfielder','Morocco'),
('Hamdi Nagguez','Defender','Tunisia'),
('Hamza Mendyl','Defender','Morocco'),
('Harold Oshkaly Cummings Segura','Defender','Panama'),
('Harry Kane','Forward','England'),
('Harry Maguire','Defender','England'),
('Hattan Babhir','Midfielder','Saudi Arabia'),
('Hee-Chan Hwang','Forward','South Korea'),
('Henrik Dalsgaard','Defender','Denmark'),
('Heung-Min Son','Forward','South Korea'),
('Hiroki Sakai','Defender','Japan'),
('Hirving Rodrigo Lozano Bahena','Forward','Mexico'),
('Hotaru Yamaguchi','Midfielder','Japan'),
('Hugo Ayala Castro','Defender','Mexico'),
('Hugo Lloris','Goalkeeper','France'),
('Hussain Al Mogahwi','Midfielder','Saudi Arabia'),
('Hyun-Soo Jang','Defender','South Korea'),
('Hyun-Woo Cho','Goalkeeper','South Korea'),
('Iago Aspas','Forward','Spain'),
('Ian Rey Smith Quiros','Midfielder','Costa Rica'),
('Idrissa Gana Gueye','Midfielder','Senegal'),
('Igor Akinfeev','Goalkeeper','Russia'),
('Igor Smolnikov','Defender','Russia'),
('Ikechukwu Ezenwa','Goalkeeper','Nigeria'),
('Ilya Kutepov','Defender','Russia'),
('Isaac Kiese Thelin','Forward','Sweden'),
('Isco','Midfielder','Spain'),
('Ja-Cheol Koo','Midfielder','South Korea'),
('Jack Butland','Goalkeeper','England'),
('Jackson Irvine','Midfielder','Australia'),
('Jae-Sung Lee','Midfielder','South Korea'),
('Jaime Manuel Penedo Cano','Goalkeeper','Panama'),
('James Meredith','Defender','Australia'),
('James Rodriguez','Midfielder','Colombia'),
('Jamie MacLaren','Forward','Australia'),
('Jamie Vardy','Forward','England'),
('Jan Bednarek','Defender','Poland'),
('Jan Vertonghen','Defender','Belgium'),
('Jannik Vestergaard','Defender','Denmark'),
('Javier Hernandez','Forward','Mexico'),
('Javier Ignacio Aquino Carmona','Midfielder','Mexico'),
('Javier Mascherano','Defender','Argentina'),
('Jefferson Lerma','Midfielder','Colombia'),
('Jens Larsen','Defender','Denmark'),
('Jesse Lingard','Midfielder','England'),
('Jhonny Acosta Zamora','Defender','Costa Rica'),
('Jimmy Durmaz','Midfielder','Sweden'),
('Jin-Hyeon Kim','Goalkeeper','South Korea'),
('Joel Nathaniel Campbell Samuels','Forward','Costa Rica'),
('Joel Obi','Midfielder','Nigeria'),
('Johan Alberto Venegas Ulloa','Midfielder','Costa Rica'),
('Johan Danon Djourou-Gbadjere','Defender','Switzerland'),
('Johan Mojica','Defender','Colombia'),
('John Guidetti','Forward','Sweden'),
('John Michael Nchekwube Obinna','Midfielder','Nigeria'),
('John Ogochukwu Ogu','Midfielder','Nigeria'),
('John Stones','Defender','England'),
('Jonas Hector','Defender','Germany'),
('Jonas Knudsen','Defender','Denmark'),
('Joo-Ho Park','Defender','South Korea'),
('Jordan Henderson','Midfielder','England'),
('Jordan Pickford','Goalkeeper','England'),
('Jordi Alba','Defender','Spain'),
('Jose Fonte','Defender','Portugal'),
('Jose Izquierdo','Forward','Colombia'),
('Josh Risdon','Defender','Australia'),
('Joshua Kimmich','Midfielder','Germany'),
('Josip Drmic','Forward','Switzerland'),
('Juan Cuadrado','Midfielder','Colombia'),
('Juan Fernando Quintero Paniagua','Midfielder','Colombia'),
('Julian Brandt','Midfielder','Germany'),
('Julian Draxler','Midfielder','Germany'),
('Kahraba','Midfielder','Egypt'),
('Kalidou Koulibaly','Defender','Senegal'),
('Kamil Glik','Defender','Poland'),
('Kamil Grosicki','Forward','Poland'),
('Karim Ansarifard','Forward','Iran'),
('Karim El Ahmadi Al Aroos','Midfielder','Morocco'),
('Karl-Johan Johnsson','Goalkeeper','Sweden'),
('Karol Linetty','Midfielder','Poland'),
('Kasper Dolberg','Forward','Denmark'),
('Kasper Schmeichel','Goalkeeper','Denmark'),
('Keisuke Honda','Midfielder','Japan'),
('Kelechi Iheanacho','Forward','Nigeria'),
('Kendall Jamaal Waston Manley','Defender','Costa Rica'),
('Kenneth Josiah Omeruo','Defender','Nigeria'),
('Kepa Arrizabalaga','Goalkeeper','Spain'),
('Kevin De Bruyne','Midfielder','Belgium'),
('Kevin Trapp','Goalkeeper','Germany'),
('Keylor Navas','Goalkeeper','Costa Rica'),
('Khadim N Diaye','Goalkeeper','Senegal'),
('Kieran Trippier','Defender','England'),
('Koen Casteels','Goalkeeper','Belgium'),
('Koke','Midfielder','Spain'),
('Kosuke Nakamura','Goalkeeper','Japan'),
('Kristoffer Nordfeldt','Goalkeeper','Sweden'),
('Kyle Walker','Defender','England'),
('Lamine Gassama','Defender','Senegal'),
('Leander Dendoncker','Midfielder','Belgium'),
('Leon Balogun','Defender','Nigeria'),
('Leon Goretzka','Midfielder','Germany'),
('Leonel Moreira Ledezma','Goalkeeper','Costa Rica'),
('Lionel Messi','Forward','Argentina'),
('Lucas Biglia','Midfielder','Argentina'),
('Lucas Torreira','Midfielder','Uruguay'),
('Ludwig Augustinsson','Defender','Sweden'),
('Luis Carlos Ovalle Victoria','Defender','Panama'),
('Luis Carlos Tejada Hansell','Forward','Panama'),
('Luis Muriel','Forward','Colombia'),
('Lukas Lerager','Midfielder','Denmark'),
('M Baye Babacar Niang','Forward','France'),
('Maciej Rybus','Defender','Poland'),
('Mahmoud Abdel Razek Fadlallah','Midfielder','Egypt'),
('Mahmoud Hamdi','Defender','Egypt'),
('Mahmoud Ibrahim Hassan','Midfielder','Egypt'),
('Makoto Hasebe','Midfielder','Japan'),
('Mame Biram Diouf','Forward','Senegal'),
('Mansour Althaqfi Al Harbi','Defender','Saudi Arabia'),
('Manuel Akanji','Defender','Switzerland'),
('Manuel Henrique Tavares Fernandes','Midfielder','Portugal'),
('Manuel Marouan da Costa Trinidade','Defender','Morocco'),
('Manuel Neuer','Goalkeeper','Germany'),
('Marcelo','Defender','Brazil'),
('Marco Asensio','Midfielder','Spain'),
('Marco Reus','Forward','Germany'),
('Marcus Berg','Forward','Sweden'),
('Marcus Rashford','Forward','England'),
('Mario Gomez','Forward','Germany'),
('Mark Milligan','Midfielder','Australia'),
('Marko Pjaca','Midfielder','Croatia'),
('Marouane Fellaini','Midfielder','Belgium'),
('Marquinhos','Defender','Brazil'),
('Martin Braithwaite','Forward','Denmark'),
('Martin Olsson','Defender','Sweden'),
('Marvin Plattenhardt','Defender','Germany'),
('Marwan Mohsen','Midfielder','Egypt'),
('Masaaki Higashiguchi','Goalkeeper','Japan'),
('Masoud Shojaei Soleimani','Midfielder','Iran'),
('Massimo Luongo','Midfielder','Australia'),
('Mathew Leckie','Midfielder','Australia'),
('Mathew Ryan','Goalkeeper','Australia'),
('Mats Hummels','Defender','Germany'),
('Matthew Jurman','Defender','Australia'),
('Matthias Ginter','Defender','Germany'),
('Maximiliano Eduardo Meza','Midfielder','Argentina'),
('Maya Yoshida','Defender','Japan'),
('Mbark Boussoufa','Midfielder','Morocco'),
('Medhi Benatia','Defender','Morocco'),
('Mehdi Taremi','Forward','Iran'),
('Mehdi Torabi','Midfielder','Iran'),
('Michael Amir Murillo Bermudez','Defender','Panama'),
('Michael Krohn-Dehli','Midfielder','Denmark'),
('Michael Lang','Defender','Switzerland'),
('Michy Batshuayi','Forward','Belgium'),
('Miguel Gianpierre Araujo Blanco','Defender','Peru'),
('Mikael Lustig','Defender','Sweden'),
('Milad Mohammadi','Defender','Iran'),
('Milan Badelj','Midfielder','Croatia'),
('Mile Jedinak','Midfielder','Australia'),
('Milos Degenek','Defender','Australia'),
('Milos Veljkovic','Midfielder','Serbia'),
('Min-Woo Kim','Midfielder','South Korea'),
('Miranda','Defender','Brazil'),
('Mohamed Abdul Shafy Sayed Abouezeid','Defender','Egypt'),
('Mohamed Amine Ben Amor','Midfielder','Tunisia'),
('Mohamed El Shenawy','Goalkeeper','Egypt'),
('Mohamed Elneny','Midfielder','Egypt'),
('Mohamed Salah','Forward','Egypt'),
('Mohammad Ibrahim Al Sahlawi','Forward','Saudi Arabia'),
('Mohammad Rashid Mazaheri','Goalkeeper','Iran'),
('Mohammad Reza Khanzadeh','Defender','Iran'),
('Mohammed Al Burayk','Defender','Saudi Arabia'),
('Mohammed Kanoo','Midfielder','Saudi Arabia'),
('Mohammed Khalil Al Owais','Goalkeeper','Saudi Arabia'),
('Mohanad Aseri Abu Radiah','Forward','Saudi Arabia'),
('Morteza Pouraliganji','Defender','Iran'),
('Motaz Ali Hassan Hawsawi','Defender','Saudi Arabia'),
('Mouez Hassen','Goalkeeper','France'),
('Moussa Dembele','Midfielder','Belgium'),
('Moussa Sow','Forward','Senegal'),
('Munir Mohand Mohamedi','Goalkeeper','Morocco'),
('Nabil Dirar','Midfielder','Morocco'),
('Nabil Fekir','Forward','France'),
('Nacer Chadli','Midfielder','Belgium'),
('Nacho Fernandez','Defender','Spain'),
('Nacho Monreal','Defender','Spain'),
('Nahuel Ignacio Guzm??n','Goalkeeper','Argentina'),
('Naomichi Ueda','Defender','Japan'),
('Neymar','Forward','Brazil'),
('Nick Pope','Goalkeeper','England'),
('Nico Elvedi','Defender','Switzerland'),
('Nicolas Otamendi','Defender','Argentina'),
('Nilson Evair Loyola Morales','Defender','Peru'),
('Nordin Amrabat','Midfielder','Morocco'),
('Odion Jude Ighalo','Forward','Nigeria'),
('Ogenyi Eddy Onazi','Midfielder','Nigeria'),
('Oghenekaro Etebo','Forward','Nigeria'),
('Ola Toivonen','Forward','Sweden'),
('Olivier Giroud','Forward','France'),
('Omar Gaber','Defender','Egypt'),
('Omar Ibrahim Omar Othman Hawsawi','Defender','Saudi Arabia'),
('Omid Ebrahimi','Midfielder','Iran'),
('Onyinye Wilfred Ndidi','Midfielder','Nigeria'),
('Oribe Peralta Morones','Forward','Mexico'),
('Osama Abdulrezag Hawsawi','Defender','Saudi Arabia'),
('Oscar Hiljemark','Midfielder','Sweden'),
('Oussama Haddadi','Defender','Tunisia'),
('Papa Alioune N Diaye','Midfielder','Senegal'),
('Patrick Alberto Pemberton Bernard','Goalkeeper','Costa Rica'),
('Paul Pogba','Midfielder','France'),
('Paulinho','Midfielder','Brazil'),
('Paulo Dybala','Forward','Argentina'),
('Pedro Tonon Geromel','Defender','Brazil'),
('Pejman Montazeri','Defender','Iran'),
('Pepe Reina','Goalkeeper','Spain'),
('Phil Jones','Defender','England'),
('Philippe Coutinho','Midfielder','Brazil'),
('Pione Sisto','Forward','Denmark'),
('Pontus Jansson','Defender','Sweden'),
('Presnel Kimpembe','Defender','France'),
('Radamel Falcao','Forward','Colombia'),
('Raheem Sterling','Forward','England'),
('Ramadan Sobhi','Forward','Egypt'),
('Rami Bedoui','Defender','Tunisia'),
('Ramin Rezaeian','Defender','Iran'),
('Remo Freuler','Midfielder','Switzerland'),
('Renato Fabrizio Tapia Cortijo','Midfielder','Peru'),
('Renato Soares de Oliveira Augusto','Midfielder','Brazil'),
('Reza Ghoochannejhad Nournia','Forward','Iran'),
('Ricardo Andrade Quaresma Bernardo','Midfielder','Portugal'),
('Ricardo Domingos Barbosa Pereira','Defender','Portugal'),
('Ricardo Guardia Avila','Defender','Panama'),
('Robbie Kruse','Forward','Australia'),
('Robert Lewandowski','Forward','Poland'),
('Roberto Firmino','Forward','Brazil'),
('Robin Olsen','Goalkeeper','Sweden'),
('Rodney Wallace','Midfielder','Costa Rica'),
('Rodrigo','Forward','Spain'),
('Rodrigo Bentancur','Midfielder','Uruguay'),
('Roman Zobnin','Midfielder','Russia'),
('Romelu Lukaku','Forward','Belgium'),
('Rouzbeh Cheshmi','Defender','Iran'),
('Ruben Loftus-Cheek','Midfielder','England'),
('Ryota Oshima','Midfielder','Japan'),
('Saad Ali Saadeldin Samir','Defender','Egypt'),
('Saber Khalifa','Forward','Tunisia'),
('Saeid Ezatolahi Afagh','Midfielder','Iran'),
('Salem Mohammed Al Dawsari','Midfielder','Saudi Arabia'),
('Salif San??','Midfielder','Senegal'),
('Salman Mohammed Al Faraj','Midfielder','Saudi Arabia'),
('Sam Morsy','Midfielder','Egypt'),
('Saman Ghoddos','Forward','Sweden'),
('Sami Khedira','Midfielder','Germany'),
('Samuel Umtiti','Defender','France'),
('Santiago Arias Naranjo','Defender','Colombia'),
('Sardar Azmoun','Forward','Iran'),
('Se-Jong Ju','Midfielder','South Korea'),
('Sebastian Larsson','Midfielder','Sweden'),
('Sebastian Rudy','Midfielder','Germany'),
('Seon-Min Moon','Midfielder','South Korea'),
('Sergei Ignashevich','Defender','Russia'),
('Sergio Aguero','Forward','Argentina'),
('Sergio Busquets','Midfielder','Spain'),
('Sergio Ramos','Defender','Spain'),
('Serigne Modou Kara Mbodji','Midfielder','Senegal'),
('Seung-Gyu Kim','Goalkeeper','South Korea'),
('Seung-Hyeon Jung','Defender','South Korea'),
('Seung-Woo Lee','Forward','South Korea'),
('Seyed Majid Hosseini','Defender','Iran'),
('Sherif Ekramy Ahmed','Goalkeeper','Egypt'),
('Shin-Wook Kim','Forward','South Korea'),
('Shinji Kagawa','Midfielder','Japan'),
('Shinji Okazaki','Forward','Japan'),
('Simon Mignolet','Goalkeeper','Belgium'),
('Simy','Forward','Nigeria'),
('Sofyan Amrabat','Midfielder','Morocco'),
('Stephan Lichtsteiner','Defender','Switzerland'),
('Steve Mandanda','Goalkeeper','France'),
('Steven N Kemboanza Mike Christopher N Zonzi','Midfielder','France'),
('Steven Zuber','Midfielder','Switzerland'),
('Sung-Yeung Ki','Midfielder','South Korea'),
('Sverrir Ingi Ingason','Defender','Iceland'),
('Syam Ben Youssef','Defender','Tunisia'),
('S??awomir Peszko','Midfielder','Poland'),
('Taisir Jabir Al Jassim','Midfielder','Saudi Arabia'),
('Taison Barcellos Freda','Forward','Brazil'),
('Takashi Inui','Midfielder','Japan'),
('Takashi Usami','Midfielder','Japan'),
('Tarek Hamed','Midfielder','Egypt'),
('Thiago Alcantara','Midfielder','Spain'),
('Thiago Rangel Cionek','Defender','Poland'),
('Thiago Silva','Defender','Brazil'),
('Thibaut Courtois','Goalkeeper','Belgium'),
('Thomas Delaney','Midfielder','Denmark'),
('Thomas Lemar','Midfielder','France'),
('Thomas Meunier','Defender','Belgium'),
('Thomas M??ller','Forward','Germany'),
('Thomas Vermaelen','Defender','Belgium'),
('Thorgan Hazard','Forward','Belgium'),
('Tim Cahill','Forward','Australia'),
('Timo Werner','Forward','Germany'),
('Tin Jedvaj','Defender','Croatia'),
('Toby Alderweireld','Defender','Belgium'),
('Tom Rogi??','Midfielder','Australia'),
('Tomi Juri??','Forward','Australia'),
('Tomoaki Makino','Defender','Japan'),
('Toni Kroos','Midfielder','Germany'),
('Trent Alexander-Arnold','Defender','England'),
('Trent Sainsbury','Defender','Australia'),
('Tyronne Ebuehi','Defender','Nigeria'),
('Vahid Amiri','Midfielder','Iran'),
('Valentin Enrique Pimentel Armuelles','Midfielder','Panama'),
('Valon Behrami','Midfielder','Switzerland'),
('Victor Moses','Midfielder','Nigeria'),
('Viktor Claesson','Midfielder','Sweden'),
('Viktor Fischer','Forward','Denmark'),
('Vincent Kompany','Defender','Belgium'),
('Vladimir Gabulov','Goalkeeper','Russia'),
('Vladimir Granat','Defender','Russia'),
('Wahbi Khazri','Midfielder','Tunisia'),
('Wataru Endo','Defender','Japan'),
('Wilfredo Daniel Caballero','Goalkeeper','Argentina'),
('William Silva de Carvalho','Midfielder','Portugal'),
('William Troost-Ekong','Defender','Nigeria'),
('Willian','Forward','Brazil'),
('Woo-Young Jung','Midfielder','South Korea'),
('Xherdan Shaqiri','Midfielder','Switzerland'),
('Yann Sommer','Goalkeeper','Switzerland'),
('Yannick Carrasco','Midfielder','Belgium'),
('Yasir Gharsan Al Shahrani','Defender','Saudi Arabia'),
('Yasser Abdullah Al Mosailem','Goalkeeper','Saudi Arabia'),
('Yassine Bounou','Goalkeeper','Morocco'),
('Yassine Meriah','Midfielder','Tunisia'),
('Yehya Sulaiman Al Shehri','Midfielder','Saudi Arabia'),
('Yeltsin Ignacio Tejeda Valverde','Midfielder','Costa Rica'),
('Yo-Han Ko','Midfielder','South Korea'),
('Yohan Benalouane','Defender','Tunisia'),
('Yong Lee','Defender','South Korea'),
('Yoshinori Muto','Forward','Japan'),
('Young-Gwon Kim','Defender','South Korea'),
('Young-Sun Yun','Defender','South Korea'),
('Youri Tielemans','Midfielder','Belgium'),
('Youssef En-Nesyri','Forward','Morocco'),
('Youssouf Sabaly','Defender','France'),
('Yuri Zhirkov','Midfielder','Russia'),
('Yury Gazinskiy','Midfielder','Russia'),
('Yussuf Poulsen','Forward','Denmark'),
('Yuto Nagatomo','Defender','Japan'),
('Yvon Mvogo','Goalkeeper','Switzerland')
